Repository couchbase/couchbase-lite-ios, pull requests merged in 2018-03, with the labels that each got.

#2080 Fix socket leaks and increase idle timeout (#2078)
  Objective-C/Internal/Replicator/CBLWebSocket.mm
Labels: review

#2086 Fix #2085 crash when canceling NSURLSession task
  Objective-C/Internal/Replicator/CBLWebSocket.mm
Labels: in progress

#2113 upgrade docs, code example
  Swift/Tests/SampleCodeTest.swift
  docs/modules/ROOT/examples/SampleCodeTest.swift
  docs/modules/ROOT/pages/swift.adoc
Labels: in progress, review

#2116 [docs] attachment size
  docs/modules/ROOT/pages/swift.adoc
Labels: in progress, review

#2123 [docs] remove mention of official tvOS support
  docs/modules/ROOT/pages/objc.adoc
  docs/modules/ROOT/pages/swift.adoc
Labels: in progress, review
